/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Control.Mercaderias_C;
import Modelos.Mercaderias_M;
import Ventanas.DetalleVentas_V;
import Ventanas.Funcionarios_V;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class vista_mercaderias extends javax.swing.JFrame {

    /**
     * Creates new form vista_mercaderias
     */
    public vista_mercaderias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbselect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtcity = new javax.swing.JTable();
        jbsearch = new javax.swing.JButton();
        jtfsearch = new javax.swing.JTextField();
        jbcancel = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jbselect.setText("Seleccionar");
        jbselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbselectActionPerformed(evt);
            }
        });

        jtcity = new JTable() {

            public boolean isCellEditable(int row, int column) {

                for (int i = 0; i < jtcity.getRowCount(); i++) {

                    if (row == i) {

                        return false;

                    }

                }

                return true;

            }

        };
        jtcity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtcity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtcityMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtcity);

        jbsearch.setText("Bucar");
        jbsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsearchActionPerformed(evt);
            }
        });

        jtfsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfsearchKeyPressed(evt);
            }
        });

        jbcancel.setText("Cancelar");
        jbcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfsearch)
                        .addGap(18, 18, 18)
                        .addComponent(jbsearch))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbselect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 115, Short.MAX_VALUE)
                                .addComponent(jbcancel)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbcancel)
                            .addComponent(jbselect)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbsearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbselectActionPerformed

        nombre = jtfsearch.getText();
        DetalleVentas_V.tfmercaderia.setText(nombre);
        DetalleVentas_V.tfmercaderia.requestFocus();
        DetalleVentas_V.tfinicio.setText("2");
        dispose();

    }//GEN-LAST:event_jbselectActionPerformed

    private void jtcityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtcityMouseClicked

        dtm = (DefaultTableModel) this.jtcity.getModel();
        int selRow = this.jtcity.getSelectedRow();

        if (evt.getClickCount() == 2) {

            String id = jtcity.getValueAt(selRow, 0).toString();
            Mercaderias_C finded = m.Consult(id);
            jtfsearch.setText(String.valueOf(finded.getCodigo()));
            nombre = jtfsearch.getText();
            DetalleVentas_V.tfmercaderia.setText(nombre);
            DetalleVentas_V.tfmercaderia.requestFocus();
            DetalleVentas_V.tfinicio.setText("2");
            this.dispose();

        } else {

            String id = String.valueOf(jtcity.getValueAt(selRow, 0));
            Mercaderias_C finded = m.Consult(id);
            jtfsearch.setText(finded.getCodigo());

        }

    }//GEN-LAST:event_jtcityMouseClicked

    private void jbsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsearchActionPerformed

        consult(jtfsearch.getText());

    }//GEN-LAST:event_jbsearchActionPerformed

    private void jbcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelActionPerformed

        this.dispose();

    }//GEN-LAST:event_jbcancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        star();
        
    }//GEN-LAST:event_formWindowOpened

    private void jtfsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfsearchKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (jtfsearch.equals("")) {
                
                jtfsearch.requestFocus();
                
            } else {
            
                this.jbsearchActionPerformed(null);
            
            }
            
        }
        
    }//GEN-LAST:event_jtfsearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_mercaderias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_mercaderias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_mercaderias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_mercaderias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_mercaderias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbcancel;
    private javax.swing.JButton jbsearch;
    private javax.swing.JButton jbselect;
    private javax.swing.JTable jtcity;
    private javax.swing.JTextField jtfsearch;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel dtm;
    private String nombre;
    private final Mercaderias_C m = new Mercaderias_C();
    
    public void consult (String search) {
    
        dtm = (DefaultTableModel) jtcity.getModel();
        ArrayList<Mercaderias_C> list = m.SearchCodigo(search);
        update();

        for (Mercaderias_M res : list) {

            dtm.addRow(new Object[]{res.getCodigo(), res.getNombre(), res.getDescripcion()});
            
        }
    
    }

    private void update (){

        int tam = jtcity.getRowCount();
        
        for (int i = 0; i < tam; i++) {
            
            dtm.removeRow(0);
            
        }

    }
    
    private void star () {
    
        dtm = (DefaultTableModel) jtcity.getModel();
        ArrayList<Mercaderias_C> var1 = m.SearchAll();
        
        for (Mercaderias_M var2 : var1) {
            
            dtm.addRow(new Object[]{var2.getCodigo(), var2.getNombre(), var2.getDescripcion()});
            
        }
    
    }

}
