/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Control.AperturaCierre_C;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AperturaCierre_V extends javax.swing.JFrame {

    /**
     * Creates new form AperturaCierre_V
     */
    public AperturaCierre_V() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        topenclose = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfcode = new javax.swing.JTextField();
        tfdate = new javax.swing.JTextField();
        tfcollected = new javax.swing.JTextField();
        tfjob = new javax.swing.JTextField();
        bsave = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        brefresh = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("APERTURA Y CIERRE DE CAJA");

        topenclose.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Fecha", "Total Recaudado", "Funcionario"
            }
        ));
        topenclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topencloseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(topenclose);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 7, 0, 7, 0, 7, 0};
        jPanel1Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel2.setText("Codigo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Total Recaudado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Funcionario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel5, gridBagConstraints);

        tfcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfcodeKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(tfcode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 91;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(tfdate, gridBagConstraints);

        tfcollected.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfcollectedKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(tfcollected, gridBagConstraints);

        tfjob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfjobKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(tfjob, gridBagConstraints);

        bsave.setText("Registrar");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(bsave, gridBagConstraints);

        bupdate.setText("Modificar");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(bupdate, gridBagConstraints);

        brefresh.setText("Actualizar");
        brefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brefreshActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(brefresh, gridBagConstraints);

        bexit.setText("Salir");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(bexit, gridBagConstraints);

        jLabel6.setText("<-- Inserte su codigo de Funcionario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel6, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        
        Count();
        id = getInt(tfcode.getText());
        fecha = tfdate.getText();
        total = tfcollected.getText();
        fun = Integer.parseInt(tfjob.getText());
        
        if ((id <= 0) && (fecha.isEmpty()) && (fun <=0)) {
            
            JOptionPane.showMessageDialog(rootPane, "Complete los campos");
            
        } else {
        
            AperturaCierre_C ap = new AperturaCierre_C(id, fecha, total, fun);
            AperturaCierre_C already = ap.Search(String.valueOf(id));
            
            if (already == null) {
                
                if (ap.Insert()) {
                    
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado con exito");
                    
                } else {
                
                    JOptionPane.showMessageDialog(rootPane, "El codigo u otro dato ya existe");
                
                }
                
                dtm = (DefaultTableModel) topenclose.getModel();
                int rows = topenclose.getRowCount();
                
                for (int i = 0; rows < i; i++) {
                    
                    dtm.removeRow(0);
                    
                }
                
                this.update();
                this.star();
                this.clean();
                
            }
            
        
        }
        
    }//GEN-LAST:event_bsaveActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        
        this.tfcode.setEditable(true);
        this.tfcollected.setEditable(true);
        this.tfjob.setEditable(true);
        this.tfdate.setEditable(false);
        this.bsave.setEnabled(false);
        
    }//GEN-LAST:event_bupdateActionPerformed

    private void brefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brefreshActionPerformed
        
        id = getInt(tfcode.getText());
        fecha = tfdate.getText();
        total = tfcollected.getText();
        fun = getInt(tfjob.getText());
        
        AperturaCierre_C apci = new AperturaCierre_C(id, fecha, total, fun);
        if(apci.Update()){
            
            JOptionPane.showMessageDialog(rootPane, "Registro modficado");
            this.update();
            this.star();
            
        } else {
            
            JOptionPane.showMessageDialog(rootPane, "No modificado");
            
        }
        
    }//GEN-LAST:event_brefreshActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_bexitActionPerformed

    private void tfcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcodeKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (tfcode.getText().equals("")) {
                
                this.tfcode.requestFocus();
                
            } else {
            
                this.tfcollected.requestFocus();
                
            }
            
        }
        
    }//GEN-LAST:event_tfcodeKeyPressed

    private void tfcollectedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcollectedKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (tfcollected.getText().equals("")) {
                
                this.tfcollected.requestFocus();
                
            } else {
            
                this.tfjob.requestFocus();
                
            }
            
        }
        
    }//GEN-LAST:event_tfcollectedKeyPressed

    private void tfjobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfjobKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (tfjob.getText().equals("")) {
                
                this.tfjob.requestFocus();
                
            } else {
            
                this.bsaveActionPerformed(null);
                
            }
            
        }
        
    }//GEN-LAST:event_tfjobKeyPressed

    private void topencloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topencloseMouseClicked
        
        try {
            
            dtm = (DefaultTableModel) this.topenclose.getModel();
            int selRow = this.topenclose.getSelectedRow();
            this.bupdate.setEnabled(true);
            this.bsave.setEnabled(false);

            if(selRow != -1){

                String id = String.valueOf(dtm.getValueAt(selRow, 0).toString());
                AperturaCierre_C finded = ac.Search(id);

                if(!(finded == null)){

                    this.tfcode.setText(String.valueOf(finded.getId()));
                    this.tfcode.setEditable(false);
                    this.tfdate.setText(finded.getDate());
                    this.tfdate.setEditable(false);
                    this.tfcollected.setText(finded.getCollect());
                    this.tfcollected.setEditable(false);
                    this.tfjob.setText(String.valueOf(finded.getFun()));
                    this.tfjob.setEditable(false);

                 }

            }
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Error al encontrar archivo"+e);
            
        }
        
    }//GEN-LAST:event_topencloseMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        star();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AperturaCierre_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AperturaCierre_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AperturaCierre_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AperturaCierre_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AperturaCierre_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit;
    private javax.swing.JButton brefresh;
    private javax.swing.JButton bsave;
    private javax.swing.JButton bupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfcode;
    private javax.swing.JTextField tfcollected;
    private javax.swing.JTextField tfdate;
    private javax.swing.JTextField tfjob;
    private javax.swing.JTable topenclose;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel dtm;
    public int id, fun;
    public String fecha, total;
    private final AperturaCierre_C ac = new AperturaCierre_C();
    
    public void Count () {
    
        try {
            
            tfcode.setText(ac.New());
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }
    
    private void clean () {
    
        tfcode.setText("");
        tfcollected.setText("");
        tfjob.setText("");
    
    }
    
    private void update () {
        
        int tam = topenclose.getRowCount();
        
        for (int i = 0; i < tam; i++) {
            
            dtm.removeRow(0);
            
        }
        
    }

    private void star () {
        
        dtm = (DefaultTableModel) topenclose.getModel();
        ArrayList<AperturaCierre_C> all = ac.SearchAll();
        
        for(int i=0; i < all.size(); i++ ){
            
            dtm.addRow(new Object[]{all.get(i).getId(), all.get(i).getDate(), all.get(i).getCollect(), all.get(i).getFun()});
            
        }
        
        this.tfdate.setText(AperturaCierre_C.fechaActual());
        
    }
    
    public static Integer getInt(String cadena){
        
        return ( (cadena == null || cadena.isEmpty() ) ? 0 : Integer.parseInt(cadena.trim()));
        
    }
    
    public static String getString(String cadena){
        
        return (cadena == null ? "" : cadena);
        
    }

}
