/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Control.CargosC;
import Control.Ciudades_C;
import Control.Funcionarios_C;
import Control.Usuarios_C;
import Ventanas.Funcionarios_V;
import Vistas.vista_usuarios;
import Vistas.vista_ciudades;
import Vistas.vista_ciudades1;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sun.management.GcInfoCompositeData;

/**
 *
 * @author User
 */
public class Cargar_Funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form Cargar_Funcionarios
     */
    public Cargar_Funcionarios() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfcode = new javax.swing.JTextField();
        tfname = new javax.swing.JTextField();
        tfidentification = new javax.swing.JTextField();
        tftelephone = new javax.swing.JTextField();
        tfdirection = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboffice = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfcity = new javax.swing.JTextField();
        tfuser = new javax.swing.JTextField();
        bsearchc = new java.awt.Button();
        bsearchusu = new java.awt.Button();
        tfcityname = new javax.swing.JTextField();
        tfusername = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        bnew = new javax.swing.JButton();
        bsave = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        bcancel = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos del Funcionario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tomar Datos"));

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombre");

        jLabel3.setText("Cedula");

        jLabel4.setText("Telefono");

        jLabel5.setText("Direccion");

        tfcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfcodeKeyPressed(evt);
            }
        });

        tfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfnameKeyPressed(evt);
            }
        });

        tfidentification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfidentificationKeyPressed(evt);
            }
        });

        tftelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tftelephoneKeyPressed(evt);
            }
        });

        tfdirection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfdirectionKeyPressed(evt);
            }
        });

        jLabel6.setText("Cargo");

        jLabel7.setText("Cod. Ciudad");

        jLabel8.setText("Cod. Usuario");

        cboffice.setOpaque(false);
        cboffice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbofficeKeyPressed(evt);
            }
        });

        jLabel9.setText("Ciudad");

        jLabel10.setText("Usuario");

        tfcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfcityKeyPressed(evt);
            }
        });

        tfuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfuserKeyPressed(evt);
            }
        });

        bsearchc.setLabel("...");
        bsearchc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearchcActionPerformed(evt);
            }
        });

        bsearchusu.setLabel("...");
        bsearchusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearchusuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(tfcode, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addGap(104, 104, 104)
                        .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41)
                        .addComponent(tfidentification, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(102, 102, 102)
                        .addComponent(tftelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(31, 31, 31)
                        .addComponent(tfdirection, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addComponent(cboffice, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(15, 15, 15)
                        .addComponent(tfcity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel9)
                        .addGap(106, 106, 106)
                        .addComponent(tfcityname, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(bsearchc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(tfuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel10)
                        .addGap(105, 105, 105)
                        .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(bsearchusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfidentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tfcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9))
                    .addComponent(tfcityname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsearchc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tfuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10))
                    .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsearchusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Comandos"));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 59, 0, 59, 0, 59, 0};
        jPanel2Layout.rowHeights = new int[] {0};
        jPanel2.setLayout(jPanel2Layout);

        bnew.setText("Nuevo");
        bnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(bnew, gridBagConstraints);

        bsave.setText("Guardar");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        bsave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bsaveKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(bsave, gridBagConstraints);

        bupdate.setText("Actualizar");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(bupdate, gridBagConstraints);

        bcancel.setText("Cancelar");
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(bcancel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewActionPerformed

        this.updateOffice();
        this.star();
        this.Count();
        this.tfname.requestFocus();
        
    }//GEN-LAST:event_bnewActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        
        try {
        
            this.getValueCB();
            code = getInt(tfcode.getText());
            name = tfname.getText();
            ci = tfidentification.getText();
            telephone = tftelephone.getText();
            direction = tfdirection.getText();
            city = getInt(tfcity.getText());
            office = getInt(jTextField1.getText());
            user = getInt(tfuser.getText());

            if ((code <= 0) || (name.isEmpty()) || (ci.isEmpty())) {

                JOptionPane.showMessageDialog(rootPane, "No registrada \nComplete todos los campos");

            } else {

                Funcionarios_C cod = new Funcionarios_C(code, name, ci, telephone, direction, city, office, user);
                Funcionarios_C ok = cod.Search(String.valueOf(code));

                if (ok == null) {

                    if (cod.Insert()) {

                        JOptionPane.showMessageDialog(rootPane, "Registrado con exito");
                        this.clean();

                    } else {

                        JOptionPane.showMessageDialog(rootPane, "No registrado \n Complete los campos");

                    }

                } else {

                    JOptionPane.showMessageDialog(rootPane, "Ya existe");

                }

                this.updateOffice();

            }
            
        } catch (Exception e) {
        
            System.err.println(e);
        
        }
        
    }//GEN-LAST:event_bsaveActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        
        this.getValueCB();
        code = getInt(tfcode.getText());
        ci = tfidentification.getText();
        name = tfname.getText();
        telephone = tftelephone.getText();
        direction = tfdirection.getText();
        city = getInt(tfcity.getText());
        office = getInt(jTextField1.getText());
        user = getInt(tfuser.getText());
        Funcionarios_C fun = new Funcionarios_C(code, name, ci, telephone, direction, city, office, user);
        
        if (fun.Update()) {
            
            JOptionPane.showMessageDialog(rootPane, "Registro modficado");
            this.star();
            
        } else {
        
            JOptionPane.showMessageDialog(rootPane, "No modificado");
        
        }
        
    }//GEN-LAST:event_bupdateActionPerformed

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        
        this.clean();
        this.dispose();

        
    }//GEN-LAST:event_bcancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        this.star();
        
    }//GEN-LAST:event_formWindowOpened

    private void tfcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcodeKeyPressed
        
        try {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
                if (tfcode.getText().equals("")) {

                    this.tfcode.requestFocus();

                } else {

                    this.tfname.requestFocus();

                }

            }
            
        } catch (Exception e) {
            
            System.err.println(e + "El codigo ya existe");
            
        }
        
    }//GEN-LAST:event_tfcodeKeyPressed

    private void tfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnameKeyPressed
        
        try {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
                if (tfname.equals("")) {

                    this.tfname.requestFocus();

                } else {

                    this.tfidentification.requestFocus();

                }

            }
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }//GEN-LAST:event_tfnameKeyPressed

    private void tfidentificationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfidentificationKeyPressed
        
        try {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
                if (tfidentification.equals("")) {

                    this.tfidentification.requestFocus();

                } else {

                    this.tftelephone.requestFocus();

                }

            }
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }//GEN-LAST:event_tfidentificationKeyPressed

    private void tftelephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tftelephoneKeyPressed
        
        try {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
                if (tftelephone.getText().equals("")) {

                    this.tftelephone.requestFocus();

                } else {

                    this.tfdirection.requestFocus();

                }

            }
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }//GEN-LAST:event_tftelephoneKeyPressed

    private void tfdirectionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdirectionKeyPressed
        
        try {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
                if (tfdirection.equals("")) {

                    this.tfdirection.requestFocus();

                } else {

                    this.cboffice.requestFocus();

                }

            }
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }//GEN-LAST:event_tfdirectionKeyPressed

    private void cbofficeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbofficeKeyPressed
        
        try {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
                if (cboffice.getSelectedIndex() == -1) {

                    this.cboffice.requestFocus();

                } else {

                    this.tfcity.requestFocus();

                }

            }
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }//GEN-LAST:event_cbofficeKeyPressed

    private void tfcityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcityKeyPressed
        
        try {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
                if (tfcity.equals(null)) {
                    
                    tfcity.requestFocus();
                    
                }
                
                int id = getInt(tfcity.getText());
                tfcityname.setText(ciu.CulsultName(id));
                
                if (tfcityname.getText().equals("")) {
                
                    JOptionPane.showMessageDialog(rootPane, "No hay ciudad con el codigo ingresado \nDigite otro codigo o busque manualnente");
                
                } else {
                    
                    tfuser.requestFocus();
                
                }

            }
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }//GEN-LAST:event_tfcityKeyPressed

    private void tfuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfuserKeyPressed
        
        try {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
                if (tfuser.equals(null)) {
                    
                    tfuser.requestFocus();
                    
                }
                
                int id = getInt(tfuser.getText());
                tfusername.setText(us.CulsultUser(id));
                
                if (tfusername.getText().equals("")) {
                
                    JOptionPane.showMessageDialog(rootPane, "No hay usuario con el codigo ingresado \nDigite otro codigo o busque manualnente");
                
                } else {
                    
                    bsave.requestFocus();
                
                }

            }
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }//GEN-LAST:event_tfuserKeyPressed

    private void bsaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bsaveKeyPressed
        
        try {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
                this.bsaveActionPerformed(null);

            }
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }//GEN-LAST:event_bsaveKeyPressed

    private void bsearchcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsearchcActionPerformed
        
        vista_ciudades1 vc = new vista_ciudades1(this, false);
        vc.setVisible(true);
        
    }//GEN-LAST:event_bsearchcActionPerformed

    private void bsearchusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsearchusuActionPerformed
        
        vista_usuarios vu = new vista_usuarios(this, false);
        vu.setVisible(true);
       
    }//GEN-LAST:event_bsearchusuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar_Funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bnew;
    private javax.swing.JButton bsave;
    private java.awt.Button bsearchc;
    private java.awt.Button bsearchusu;
    private javax.swing.JButton bupdate;
    public static javax.swing.JComboBox cboffice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField tfcity;
    public static javax.swing.JTextField tfcityname;
    public static javax.swing.JTextField tfcode;
    public static javax.swing.JTextField tfdirection;
    public static javax.swing.JTextField tfidentification;
    public static javax.swing.JTextField tfname;
    public static javax.swing.JTextField tftelephone;
    public static javax.swing.JTextField tfuser;
    public static javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables

    private final Funcionarios_C f = new Funcionarios_C();
    private final Ciudades_C ciu = new Ciudades_C();
    private final Usuarios_C us = new Usuarios_C();
    private final CargosC c = new CargosC();
    private int code, city, office, user;
    private String name, ci, telephone, direction;
    
    private void Count () {
    
        try {
            
            tfcode.setText(f.New());
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }
    
    private void clean () {
    
        this.tfcity.setText("");
        this.tfcityname.setText("");
        this.tfcode.setText("");
        this.tfdirection.setText("");
        this.tfidentification.setText("");
        this.tfname.setText("");
        this.tftelephone.setText("");
        this.tfuser.setText("");
        this.tfusername.setText("");
        
    }
    
    private void getValueCB () {
    
        String cargo = cboffice.getSelectedItem().toString().trim();
        CargosC result = c.ConsultId(cargo);
        
        if (!(result == null)) {
            
            jTextField1.setText(String.valueOf(result.getId()));
            
        }
    
    }
    
    private void updateOffice() {
        
        int count = cboffice.getItemCount();
        
        for (int i = 0; i < count; i++) {
            
            cboffice.removeItemAt(0);
            
        }
        
    }
    
    private void star () {
    
        ArrayList<CargosC> lista = c.SearchAll();
        
        for (int i = 0; i < lista.size(); i++) {
            
            cboffice.addItem(lista.get(i).getName().trim());
            
        }
        
        this.cboffice.setSelectedIndex(-1);
        
    }
    
    public static Integer getInt(String cadena){
        return ( (cadena == null || cadena.isEmpty() ) ? 0 : Integer.parseInt(cadena.trim()));
    }

}
