/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ContolesVista.vista_detalle_ventas;
import Control.Clientes_C;
import Control.DetalleVentas_C;
import Control.Funcionarios_C;
import Control.Mercaderias_C;
import Control.Ventas_C;
import Vistas.vista_clientes;
import Vistas.vista_mercaderias;
import Vistas.vista_vendedores;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class DetalleVentas_V extends javax.swing.JFrame {

    /**
     * Creates new form DetalleVentas_V
     */
    public DetalleVentas_V() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tdetalleventa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfmercaderia = new javax.swing.JTextField();
        bbuscarmercaderia = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        tfcantdad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfprecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfpreciofinal = new javax.swing.JTextField();
        bcargar = new javax.swing.JButton();
        bsacar = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfcliente = new javax.swing.JTextField();
        tfclientename = new javax.swing.JTextField();
        bbuscarvendedor = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        tffactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfvendedor = new javax.swing.JTextField();
        tfvendedorname = new javax.swing.JTextField();
        bbuscarcliente = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();
        tffecha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfventa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfmonto = new javax.swing.JTextField();
        bguardar = new javax.swing.JButton();
        bcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detalle Ventas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tdetalleventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio unitario", "Monto total"
            }
        ));
        jScrollPane1.setViewportView(tdetalleventa);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cargar productos"));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0};
        jPanel1Layout.rowHeights = new int[] {0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel5.setText("Codigo del producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel5, gridBagConstraints);

        tfmercaderia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfmercaderiaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 86;
        jPanel1.add(tfmercaderia, gridBagConstraints);

        bbuscarmercaderia.setLabel("...");
        bbuscarmercaderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarmercaderiaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bbuscarmercaderia, gridBagConstraints);

        jLabel6.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel6, gridBagConstraints);

        tfcantdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfcantdadKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 37;
        jPanel1.add(tfcantdad, gridBagConstraints);

        jLabel7.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel7, gridBagConstraints);

        tfprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfprecioKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 72;
        jPanel1.add(tfprecio, gridBagConstraints);

        jLabel8.setText("Precio por cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel8, gridBagConstraints);

        tfpreciofinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfpreciofinalKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 84;
        jPanel1.add(tfpreciofinal, gridBagConstraints);

        bcargar.setText("Cargar");
        bcargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcargarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bcargar, gridBagConstraints);

        bsacar.setLabel("X");
        bsacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsacarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bsacar, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Detalle de venta"));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 7, 0, 7, 0, 7, 0};
        jPanel2Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setText("Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jLabel1, gridBagConstraints);

        tfcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfclienteKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(tfcliente, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.insets = new java.awt.Insets(0, 26, 0, 0);
        jPanel2.add(tfclientename, gridBagConstraints);

        bbuscarvendedor.setLabel("...");
        bbuscarvendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarvendedorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(bbuscarvendedor, gridBagConstraints);

        jLabel2.setText("Factura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jLabel2, gridBagConstraints);

        tffactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tffacturaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 152;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(tffactura, gridBagConstraints);

        jLabel3.setText("Vendedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jLabel3, gridBagConstraints);

        tfvendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfvendedorKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(tfvendedor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.insets = new java.awt.Insets(0, 26, 0, 0);
        jPanel2.add(tfvendedorname, gridBagConstraints);

        bbuscarcliente.setLabel("...");
        bbuscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarclienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(bbuscarcliente, gridBagConstraints);

        jLabel4.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 153;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(tffecha, gridBagConstraints);

        jLabel11.setText("Codigo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(tfventa, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 7, 0, 7, 0, 7, 0};
        jPanel3Layout.rowHeights = new int[] {0};
        jPanel3.setLayout(jPanel3Layout);

        jLabel9.setText("Monto total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 93;
        jPanel3.add(tfmonto, gridBagConstraints);

        bguardar.setText("Guardar");
        bguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(bguardar, gridBagConstraints);

        bcancelar.setText("Cancelar");
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(bcancelar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfclienteKeyPressed
        
        this.tfclientename.setEditable(false);
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            cliente = getInt(tfcliente.getText());
            Clientes_C values = new Clientes_C(cliente, fecha, factura, importe, ajustedesc, precio);
            Clientes_C conult = values.Search(String.valueOf(cliente));
            
            if (tfcliente.getText().equals(null) || conult == null) {
                JOptionPane.showMessageDialog(rootPane, "El codigo no se encontro. \nIngrese nuevamente el codigo o busque manuealmente");
                tfcliente.setText("");
                tfcliente.requestFocus();
                
            } else {
            
                int id = getInt(tfcliente.getText());
                tfclientename.setText(c.CulsultName(id));
                tffactura.requestFocus();
            
            }
            
        }
        
    }//GEN-LAST:event_tfclienteKeyPressed

    private void tffacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tffacturaKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (tffactura.getText().equals(null)) {
                
                tffactura.requestFocus();
                
            } else {
            
                tfvendedor.requestFocus();
            
            }
            
        }
        
    }//GEN-LAST:event_tffacturaKeyPressed

    private void tfvendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfvendedorKeyPressed
        
        this.tfvendedorname.setEditable(false);
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            funcionario = getInt(tfvendedor.getText());
            Funcionarios_C values = new Funcionarios_C(funcionario, fecha, mercaderia, importe, ajustedesc, precio, cantidad, preciof);
            Funcionarios_C conult = values.Search(String.valueOf(funcionario));
            
            if (tfvendedor.getText().equals(null) || conult == null) {
                JOptionPane.showMessageDialog(rootPane, "El codigo no se encontro. \nIngrese nuevamente el codigo o busque manuealmente");
                tfvendedor.setText("");
                tfvendedor.requestFocus();
                
            } else {
            
                int id = getInt(tfvendedor.getText());
                tfvendedorname.setText(f.CulsultName(id));
                
                //Se realiza el insert de venta
                venta = getInt(tfventa.getText());
                cliente = getInt(tfcliente.getText());
                funcionario = getInt(tfvendedor.getText());
                factura = tffactura.getText();
                fecha = tffecha.getText();
                
                Ventas_C val = new Ventas_C(venta, fecha, factura, cliente, funcionario);
                val.Insert();
                System.out.println("Se cargo exitosamente la la tabla de venta");
                tfmercaderia.requestFocus();
                
            }
            
        }
        
    }//GEN-LAST:event_tfvendedorKeyPressed

    private void tfmercaderiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmercaderiaKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            mercaderia = tfmercaderia.getText();
            Mercaderias_C res = m.Consult2(mercaderia);
            
            if (mercaderia.isEmpty() || res == null) {
                
                JOptionPane.showMessageDialog(rootPane, "El codigo no se encontro. \nIngrese nuevamente el codigo o busque manuealmente");
                tfmercaderia.setText("");
                tfmercaderia.requestFocus();
                
            } else {
            
                mercaderia = tfmercaderia.getText();
                tfprecio.setText(m.CulsultPrice(mercaderia));
                tfcantdad.requestFocus();
            
            }
            
        }
        
    }//GEN-LAST:event_tfmercaderiaKeyPressed

    private void bcargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcargarActionPerformed
        
        venta = getInt(tfventa.getText());
        mercaderia = tfmercaderia.getText();
        int idmer = getInt(m.ConsultID(mercaderia));
        cantidad = getInt(tfcantdad.getText());
        precio = getInt(tfprecio.getText());
        preciof = getInt(tfpreciofinal.getText());
        
        int cons = getInt(v.Consulta(venta));
        
        if (cons == 0) {
            
            JOptionPane.showMessageDialog(rootPane, "Complete los datos del cliente antes de ingresar una mercaderia");
            tfcliente.requestFocus();
            
        } else {
        
            DetalleVentas_C values = new DetalleVentas_C(venta, idmer, cantidad, precio, preciof);
            values.Insert();
        
        }
        
        clean_mer();
        update();
        star();
        sum();
        
    }//GEN-LAST:event_bcargarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        star();
        count();
        this.jPanel1.setEnabled(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void tfcantdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcantdadKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            cantidad = getInt(tfcantdad.getText());
            
            if (cantidad <= 0) {
                
                tfcantdad.requestFocus();
                
            } else {
            
                cantidad = getInt(tfcantdad.getText());
                precio = getInt(tfprecio.getText());
                int value = cantidad * precio;
                tfpreciofinal.setText(String.valueOf(value));
                tfprecio.requestFocus();
            
            }
            
        }
        
    }//GEN-LAST:event_tfcantdadKeyPressed

    private void tfprecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfprecioKeyPressed
        
        tfprecio.setEditable(false);
        
        if (tfprecio.equals(null)) {
            
            tfmercaderia.requestFocus();
            tfprecio.setEditable(false);
            
        } else {
        
            this.tfprecio.setEditable(false);
            tfpreciofinal.requestFocus();
        
        }
        
        tfprecio.setEditable(false);
        
    }//GEN-LAST:event_tfprecioKeyPressed

    private void tfpreciofinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpreciofinalKeyPressed
        
        tfpreciofinal.setEditable(false);
        
        if (tfpreciofinal.equals(null)) {
            
            tfmercaderia.requestFocus();
            tfpreciofinal.setEditable(false);
            
        } else {
        
            this.tfpreciofinal.setEditable(false);
            this.bcargarActionPerformed(null);
            this.tfmercaderia.requestFocus();
        
        }
        
        tfpreciofinal.setEditable(false);
        
    }//GEN-LAST:event_tfpreciofinalKeyPressed

    private void bguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguardarActionPerformed
        
        JOptionPane.showMessageDialog(rootPane, "Guardado y en espera de confirmacion");
        update();
        clean_ven();
        
    }//GEN-LAST:event_bguardarActionPerformed

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        
        int value = JOptionPane.showConfirmDialog(rootPane, "Desea cancelar la operacion?");
        
        if (value == 0) {
            
            venta = getInt(tfventa.getText());
            dv.DeleteAll(venta);
            Ventas_C res = v.Search(String.valueOf(venta));
            
            if (res == null) {
                
                clean_ven();
                clean_mer();
                
            } else {
            
                String val = tfventa.getText();
                v.Delete(String.valueOf(val));
                clean_ven();
                clean_mer();
                update();
            
            }
            
        } else if (value == 1) {
        
        } else {
        
        }
        
    }//GEN-LAST:event_bcancelarActionPerformed

    private void bsacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsacarActionPerformed
        
        try {
            
            dtm = (DefaultTableModel)tdetalleventa.getModel();
            int selrow = tdetalleventa.getSelectedRow();
            
            if (selrow != -1) {
                
                String mer = String.valueOf(dtm.getValueAt(selrow, 0));
                int id = getInt(m.ConsultID(mer));
                dv.Delete(String.valueOf(id));
                
                update();
                star();
                sum();
                
            } else {
            
                JOptionPane.showMessageDialog(rootPane, "Seleccione un item");
            
            }
            
            this.update();
            this.star();
            this.sum();
            
            
        } catch (Exception e) {
            
            System.err.println(e.getMessage());
            
        }
        
    }//GEN-LAST:event_bsacarActionPerformed

    private void bbuscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarclienteActionPerformed
        
        vista_clientes vc = new vista_clientes();
        vc.setVisible(true);
        
    }//GEN-LAST:event_bbuscarclienteActionPerformed

    private void bbuscarvendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarvendedorActionPerformed
        
        vista_vendedores vv = new vista_vendedores();
        vv.setVisible(true);
        
    }//GEN-LAST:event_bbuscarvendedorActionPerformed

    private void bbuscarmercaderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarmercaderiaActionPerformed
        
        vista_mercaderias vm = new vista_mercaderias();
        vm.setVisible(true);
        
    }//GEN-LAST:event_bbuscarmercaderiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleVentas_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleVentas_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleVentas_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleVentas_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleVentas_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bbuscarcliente;
    private java.awt.Button bbuscarmercaderia;
    private java.awt.Button bbuscarvendedor;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton bcargar;
    private javax.swing.JButton bguardar;
    private java.awt.Button bsacar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tdetalleventa;
    private javax.swing.JTextField tfcantdad;
    public static javax.swing.JTextField tfcliente;
    public static javax.swing.JTextField tfclientename;
    public static javax.swing.JTextField tffactura;
    public static javax.swing.JTextField tffecha;
    public static javax.swing.JTextField tfmercaderia;
    private javax.swing.JTextField tfmonto;
    private javax.swing.JTextField tfprecio;
    private javax.swing.JTextField tfpreciofinal;
    public static javax.swing.JTextField tfvendedor;
    public static javax.swing.JTextField tfvendedorname;
    public static javax.swing.JTextField tfventa;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel dtm;
    
    private final vista_detalle_ventas vdv = new vista_detalle_ventas();
    private final DetalleVentas_C dv = new DetalleVentas_C();
    private final Ventas_C v = new Ventas_C();
    private final Clientes_C c = new Clientes_C();
    private final Mercaderias_C m = new Mercaderias_C();
    private final Funcionarios_C f = new Funcionarios_C();
    DecimalFormat format = new DecimalFormat("#,##0");
    private int venta, cliente, funcionario, cantidad, precio, preciof;
    private String mercaderia, fecha, factura, importe, ajustedesc;
    
    private void star() {
    
        dtm = (DefaultTableModel)tdetalleventa.getModel();
        venta = getInt(tfventa.getText());
        tfcliente.requestFocus();
        ArrayList<vista_detalle_ventas> res = vdv.Search(venta);
        
        tffecha.setText(Ventas_C.fechaActual());
        
        for (int i = 0; i < res.size() ; i++) {
            
            dtm.addRow(new Object[] {res.get(i).getProducto(), res.get(i).getCantidad(),
            res.get(i).getPrecio(), res.get(i).getMonto_final()});
            
        }
        
        this.tfventa.setEditable(false);
        this.tfclientename.setEditable(false);
        this.tfvendedorname.setEditable(false);
    
    }
    
    private void count () {
    
        tfventa.setText(v.New());
    
    }
    
    private void clean_mer () {
    
        this.tfmercaderia.setText("");
        this.tfcantdad.setText("");
        this.tfprecio.setText("");
        this.tfpreciofinal.setText("");
        this.tfmonto.setText("");
    
    }
    
    private void clean_ven () {
    
        this.tfcliente.setText("");
        this.tfmonto.setText("");
        this.tfclientename.setText("");
        this.tffactura.setText("");
        this.tfvendedor.setText("");
        this.tfvendedorname.setText("");
        tfventa.setText(v.New());
    
    }
    
    private void update () {
        
        int tam = tdetalleventa.getRowCount();
        
        for (int i = 0; i < tam; i++) {
            
            dtm.removeRow(0);
            
        }
        
    }
    
    private void sum () {
        
        int all_value = 0;
        
        for (int i = 0; i < tdetalleventa.getRowCount(); i++) {
            
            all_value += getInt(tdetalleventa.getValueAt(i, 3).toString().replace(".", ""));
            
        }
        
        tfmonto.setText(format.format(all_value));
        
    }

    public static Integer getInt(String cadena){
        
        return ( (cadena == null || cadena.isEmpty() ) ? 0 : Integer.parseInt(cadena.trim()));
        
    }
    
    public static String getString(String cadena){
        
        return (cadena == null ? "" : cadena);
        
    }
    
}