/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import static Ventanas.Cargar_Funcionarios.cboffice;
import ContolesVista.vista_funcionarios;
import Control.CargosC;
import Control.Ciudades_C;
import Control.Funcionarios_C;
import Control.Usuarios_C;
import Modelos.CargosM;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Funcionarios_V extends javax.swing.JFrame {

    /**
     * Creates new form Funcionarios_V
     */
    public Funcionarios_V(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jtclerk = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbsearch = new javax.swing.JComboBox();
        tfsearch = new javax.swing.JTextField();
        bsearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bnew = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        bactualizar = new javax.swing.JButton();
        breport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funcionarios");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtclerk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Funcionario", "Cedula", "Telefono", "Direccion", "Ciudad", "Cargo", "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtclerk);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar"));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 12, 0, 12, 0, 12, 0};
        jPanel1Layout.rowHeights = new int[] {0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("Buscar por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel1, gridBagConstraints);

        cbsearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Funcionario", "CI", "Telefono" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(cbsearch, gridBagConstraints);

        tfsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfsearchKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 302;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(tfsearch, gridBagConstraints);

        bsearch.setText("Buscar");
        bsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(bsearch, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 12, 0, 12, 0, 12, 0, 12, 0, 12, 0};
        jPanel2Layout.rowHeights = new int[] {0};
        jPanel2.setLayout(jPanel2Layout);

        bnew.setText("Nuevo");
        bnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(bnew, gridBagConstraints);

        bupdate.setText("Modificar");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel2.add(bupdate, gridBagConstraints);

        bdelete.setText("Eliminar");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel2.add(bdelete, gridBagConstraints);

        bexit.setText("Salir");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        jPanel2.add(bexit, gridBagConstraints);

        bactualizar.setText("Actualizar");
        bactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bactualizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel2.add(bactualizar, gridBagConstraints);

        breport.setText("Ver Reporte");
        breport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel2.add(breport, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewActionPerformed
        
        try {
            
            car.setVisible(true);
            Cargar_Funcionarios.bupdate.setEnabled(false);
            this.Count();
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }//GEN-LAST:event_bnewActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        
        dtm = (DefaultTableModel)jtclerk.getModel();
        int selrow = jtclerk.getSelectedRow();
        
        if (selrow != -1) {
            
            String id = String.valueOf(dtm.getValueAt(selrow, 0).toString());
            Funcionarios_C finded = f.Search(id);
            
            if (!(finded == null)) {
                
                car.setVisible(true);
                
                Cargar_Funcionarios.bsave.setEnabled(false);
                Cargar_Funcionarios.bnew.setEnabled(false);
                Cargar_Funcionarios.tfcode.setText(String.valueOf(finded.getCode()));
                Cargar_Funcionarios.tfname.setText(finded.getName());
                Cargar_Funcionarios.tfidentification.setText(finded.getCi());

//                int job = finded.getJob();
//                CargosC nom = new CargosC();
//                CargosC res = nom.Search(String.valueOf(job));
//                String cargo = res.getName();
//                Cargar_Funcionarios.cboffice.setSelectedItem(cargo);

                Cargar_Funcionarios.tftelephone.setText(finded.getTelephone());
                Cargar_Funcionarios.tfdirection.setText(finded.getDirection());
                Cargar_Funcionarios.tfcity.setText(String.valueOf(finded.getCity()));
                Cargar_Funcionarios.tfuser.setText(String.valueOf(finded.getUser()));
                Cargar_Funcionarios.jTextField1.setText("1");
                
            }
            
            this.update();
            this.star();
            
        } else {

            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro para modificar");

        }
        
    }//GEN-LAST:event_bupdateActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        
        try {
            
            dtm = (DefaultTableModel)jtclerk.getModel();
            int selrow = jtclerk.getSelectedRow();
            
            if (selrow != -1) {
                
                String id = String.valueOf(dtm.getValueAt(selrow, 0).toString());
                f.Delete(id);
                JOptionPane.showMessageDialog(rootPane, "Registro Eliminado");
                
            } else {
            
                JOptionPane.showMessageDialog(rootPane, "Seleccione primero un registro");
            
            }
            
            this.update();
            this.star();
            
            
        } catch (HeadlessException e) {
            
            System.err.println(e);
            
        }
        
    }//GEN-LAST:event_bdeleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        this.star();
        
    }//GEN-LAST:event_formWindowOpened

    private void bactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bactualizarActionPerformed
        
        this.update();
        this.star();
        
    }//GEN-LAST:event_bactualizarActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_bexitActionPerformed

    private void tfsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsearchKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (tfsearch.getText().equals("")) {
                
                this.tfsearch.requestFocus();
                
            } else {
            
                this.bsearchActionPerformed(null);
            
            }
            
        }
        
    }//GEN-LAST:event_tfsearchKeyPressed

    private void bsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsearchActionPerformed
        
        search(tfsearch.getText());
        
    }//GEN-LAST:event_bsearchActionPerformed

    private void breportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breportActionPerformed
        
        vf.showFuncionarios();

    }//GEN-LAST:event_breportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionarios_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionarios_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionarios_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionarios_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Funcionarios_V dialog = new Funcionarios_V(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bactualizar;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bnew;
    private javax.swing.JButton breport;
    private javax.swing.JButton bsearch;
    private javax.swing.JButton bupdate;
    private javax.swing.JComboBox cbsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtclerk;
    public static javax.swing.JTextField tfsearch;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel dtm;
    private final Cargar_Funcionarios car = new Cargar_Funcionarios();
    private final Funcionarios_C f = new Funcionarios_C();
    private final vista_funcionarios vf = new vista_funcionarios();
    
    private void update () {
        
        int tam = jtclerk.getRowCount();
        
        for (int i = 0; i < tam; i++) {
            
            dtm.removeRow(0);
            
        }
        
    }
    
    private void star () {
        
        dtm = (DefaultTableModel) jtclerk.getModel();
        ArrayList<vista_funcionarios> all = vf.Buscar();
        
        for(int i = 0; i < all.size(); i++ ){
            
            dtm.addRow(new Object[]{all.get(i).getCode(), all.get(i).getName(),
            all.get(i).getCi(), all.get(i).getTelephone(), all.get(i).getDirection(),
            all.get(i).getCity(), all.get(i).getOffice(), all.get(i).getUser()});
            
        }
        
    }
    
    public void search (String search) {
        
        String options = (String)cbsearch.getSelectedItem();
        dtm = (DefaultTableModel) jtclerk.getModel();
        ArrayList<vista_funcionarios> list = null;
        
        switch (options) {
            case "ID":
                list = vf.SearchID(search);                
                break;

            case "Funcionario":
                list = vf.SearchName(search);
                break;

            case "CI":
                list = vf.SearchCI(search);
                break;

            case "Telefono":
                list = vf.SearchTelephone(search);
                break;

        }
        
        if (list != null) {

            update();

            for(int i=0; i < list.size(); i++ ){
            
                dtm.addRow(new Object[]{list.get(i).getCode(), list.get(i).getName(),
                list.get(i).getCi(), list.get(i).getTelephone(), list.get(i).getDirection(),
                list.get(i).getCity(), list.get(i).getOffice(), list.get(i).getUser()});

            }

        }
    
    }
    
    public void Count () {
    
        try {
            
            car.tfcode.setText(f.New());
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
    }
    
    public static Integer getInt(String cadena){
        
        return ( (cadena == null || cadena.isEmpty() ) ? 0 : Integer.parseInt(cadena.trim()));
        
    }
    
    public static String getString(String cadena){
        
        return (cadena == null ? "" : cadena);
        
    }

}
