/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Control.Mercaderias_C;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Mercaderias_V extends javax.swing.JFrame {

    /**
     * Creates new form Mercaderias_V
     */
    public Mercaderias_V() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtmercaderias = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfcodfab = new javax.swing.JTextField();
        jtfname = new javax.swing.JTextField();
        jtfstock = new javax.swing.JTextField();
        jtfprice = new javax.swing.JTextField();
        jtfdesc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jcbopciones = new javax.swing.JComboBox();
        jtfsearch = new javax.swing.JTextField();
        jbsearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbsave = new javax.swing.JButton();
        jbupdate = new javax.swing.JButton();
        jbdelete = new javax.swing.JButton();
        jbexit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("MERCADERIAS");

        jtmercaderias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo de Fabrica", "Producto", "Stock", "Precio", "Descripcion"
            }
        ));
        jtmercaderias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtmercaderiasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtmercaderias);
        if (jtmercaderias.getColumnModel().getColumnCount() > 0) {
            jtmercaderias.getColumnModel().getColumn(0).setMaxWidth(50);
            jtmercaderias.getColumnModel().getColumn(1).setMaxWidth(250);
            jtmercaderias.getColumnModel().getColumn(2).setMaxWidth(200);
            jtmercaderias.getColumnModel().getColumn(3).setMaxWidth(100);
            jtmercaderias.getColumnModel().getColumn(4).setMaxWidth(100);
            jtmercaderias.getColumnModel().getColumn(5).setMaxWidth(300);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 12, 0, 12, 0, 12, 0};
        jPanel1Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel3.setText("Cod. Fabrica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Stock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Descripcion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel7, gridBagConstraints);

        jtfcodfab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfcodfabKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        jPanel1.add(jtfcodfab, gridBagConstraints);

        jtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfnameKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        jPanel1.add(jtfname, gridBagConstraints);

        jtfstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfstockKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        jPanel1.add(jtfstock, gridBagConstraints);

        jtfprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfpriceKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        jPanel1.add(jtfprice, gridBagConstraints);

        jtfdesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfdescKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel1.add(jtfdesc, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 7, 0, 7, 0, 7, 0};
        jPanel2Layout.rowHeights = new int[] {0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel8.setText("Buscar por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel8, gridBagConstraints);

        jcbopciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Codigo de Fabrica", "Producto", "Descripcion" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        jPanel2.add(jcbopciones, gridBagConstraints);

        jtfsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfsearchKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 215;
        jPanel2.add(jtfsearch, gridBagConstraints);

        jbsearch.setText("Buscar");
        jbsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jbsearch, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 7, 0};
        jPanel3Layout.rowHeights = new int[] {0, 10, 0, 10, 0};
        jPanel3.setLayout(jPanel3Layout);

        jbsave.setText("Guardar");
        jbsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsaveActionPerformed(evt);
            }
        });
        jbsave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbsaveKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jbsave, gridBagConstraints);

        jbupdate.setText("Modificar");
        jbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jbupdate, gridBagConstraints);

        jbdelete.setText("Eliminar");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jbdelete, gridBagConstraints);

        jbexit.setText("Salir");
        jbexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 22;
        jPanel3.add(jbexit, gridBagConstraints);

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        jPanel3.add(jButton1, gridBagConstraints);

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtmercaderiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtmercaderiasMouseClicked
        
        this.jbdelete.setEnabled(true);
        this.jbupdate.setEnabled(true);
        dtm = (DefaultTableModel) this.jtmercaderias.getModel();
        int selRow = this.jtmercaderias.getSelectedRow();
        Mercaderias_C car = new Mercaderias_C();
        
        if(selRow != -1){
            
            String id = dtm.getValueAt(selRow, 0).toString();
            Mercaderias_C finded = car.Search(id);
            
            if(!(finded == null)){
                
                this.jTextField1.setText(String.valueOf(finded.getId()));
                this.jtfcodfab.setText(finded.getCodigo());
                this.jtfname.setText(finded.getNombre());
                this.jtfstock.setText(String.valueOf(finded.getStock()));
                this.jtfprice.setText(String.valueOf(finded.getPrecio()));
                this.jtfdesc.setText(finded.getDescripcion());
                
            }
            
        }
        
    }//GEN-LAST:event_jtmercaderiasMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        this.Count();
        this.star();
        this.jTextField1.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void jtfcodfabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcodfabKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (jtfcodfab.getText().equals("")) {
                
                jtfcodfab.requestFocus();
                
            } else {
            
                jtfname.requestFocus();
                
            }
            
        }
        
    }//GEN-LAST:event_jtfcodfabKeyPressed

    private void jtfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfnameKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (jtfname.getText().equals("")) {
                
                jtfname.requestFocus();
                
            } else {
            
                jtfstock.requestFocus();
                
            }
            
        }
        
    }//GEN-LAST:event_jtfnameKeyPressed

    private void jtfstockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfstockKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (jtfstock.getText().equals("")) {
                
                jtfstock.requestFocus();
                
            } else {
            
                jtfprice.requestFocus();
                
            }
            
        }
        
    }//GEN-LAST:event_jtfstockKeyPressed

    private void jtfpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfpriceKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (jtfprice.getText().equals("")) {
                
                jtfprice.requestFocus();
                
            } else {
         
                jtfdesc.requestFocus();
                
            }
            
        }
        
    }//GEN-LAST:event_jtfpriceKeyPressed

    private void jtfdescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (jtfdesc.getText().equals("")) {
                
                jtfdesc.requestFocus();
                
            } else {
         
                jbsave.requestFocus();
                
            }
            
        }
        
    }//GEN-LAST:event_jtfdescKeyPressed

    private void jbsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsaveActionPerformed
        
        id = getInt(jTextField1.getText());
        codigo = jtfcodfab.getText();
        nombre = jtfname.getText();
        stock = getInt(jtfstock.getText());
        precio = getInt(jtfprice.getText());
        obs = jtfdesc.getText();
        
        if ((id <= 0) || (codigo.equals("")) || (nombre.equals("")) || (stock <= 0) || (precio <= 0)) {
            
            JOptionPane.showMessageDialog(rootPane, "Complete los campos requeridos");
            
        } else {
        
            Mercaderias_C m = new Mercaderias_C(id, codigo, nombre, stock, precio, obs);
            Mercaderias_C existe = m.Search(String.valueOf(id));
        
            if (existe == null) {
            
                if (m.Insert()) {
                    
                    JOptionPane.showMessageDialog(rootPane, "Registrado con exito");
                    
                } else {
                    
                    JOptionPane.showMessageDialog(rootPane, "No registrado \n Complete los campos");
                    
                }
                
            } else {
                
                JOptionPane.showMessageDialog(rootPane, "Ya existe");
                jtfcodfab.setText(existe.getCodigo());
                jtfname.setText(existe.getNombre());
                jtfstock.setText(String.valueOf(existe.getStock()));
                jtfprice.setText(String.valueOf(existe.getPrecio()));
                jtfdesc.setText(existe.getDescripcion());
                
            }
            
            dtm = (DefaultTableModel) jtmercaderias.getModel();
            int rows = jtmercaderias.getRowCount();
            for (int i = 0; rows > i; i++) {
                
                dtm.removeRow(0);
                
            }
            
            this.update();
            this.star();
        }
        
    }//GEN-LAST:event_jbsaveActionPerformed

    private void jbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdateActionPerformed
        
        id = getInt(jTextField1.getText());
        codigo = jtfcodfab.getText();
        nombre = jtfname.getText();
        stock = getInt(jtfstock.getText());
        precio = getInt(jtfprice.getText());
        obs = jtfdesc.getText();
        Mercaderias_C mm1 = new Mercaderias_C(id, codigo, nombre, stock, precio, obs);
        
        if(mm1.Update()){
            
            JOptionPane.showMessageDialog(rootPane, "Registro modficado");
            this.update();
            this.star();
            
        }else{
            
            JOptionPane.showMessageDialog(rootPane, "No modificado");
            
        }
        
    }//GEN-LAST:event_jbupdateActionPerformed

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
        
        String code = jTextField1.getText();
        Mercaderias_C mp = new Mercaderias_C();
        
        if(mp.Delete(code)){
            
            JOptionPane.showMessageDialog(this, "Eliminando satisfactoriamente");
            
        }else{
            
            JOptionPane.showMessageDialog(this, "Imposible eliminar");
            
        }
        
        this.update();
        this.star();
        this.clean();
        
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void jbexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexitActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_jbexitActionPerformed

    private void jbsaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbsaveKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            this.jbsaveActionPerformed(null);
            
        }
        
    }//GEN-LAST:event_jbsaveKeyPressed

    private void jbsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsearchActionPerformed
        
        search(jtfsearch.getText());
        
    }//GEN-LAST:event_jbsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.Count();
        this.clean();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfsearchKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (jtfsearch.equals("")) {
                
                jtfsearch.requestFocus();
                
            } else {
            
                this.jbsearchActionPerformed(null);
            
            }
            
        }
        
    }//GEN-LAST:event_jtfsearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mercaderias_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mercaderias_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mercaderias_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mercaderias_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mercaderias_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbexit;
    private javax.swing.JButton jbsave;
    private javax.swing.JButton jbsearch;
    private javax.swing.JButton jbupdate;
    private javax.swing.JComboBox jcbopciones;
    private javax.swing.JTextField jtfcodfab;
    private javax.swing.JTextField jtfdesc;
    private javax.swing.JTextField jtfname;
    private javax.swing.JTextField jtfprice;
    private javax.swing.JTextField jtfsearch;
    private javax.swing.JTextField jtfstock;
    private javax.swing.JTable jtmercaderias;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel dtm;
    public int id, stock, precio;
    public String codigo, nombre, obs;
    
    private void Count () {
    
        try {
            
            Mercaderias_C a = new Mercaderias_C();
            jTextField1.setText(a.New());
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
    
    }
    
    private void clean () {
    
        this.jtfcodfab.setText("");
        this.jtfname.setText("");
        this.jtfstock.setText("");
        this.jtfprice.setText("");
        this.jtfdesc.setText("");
    
    }
    
    private void update () {
        
        int tam = jtmercaderias.getRowCount();
        
        for (int i = 0; i < tam; i++) {
            
            dtm.removeRow(0);
            
        }
        
    }
    
    private void star () {
        
        dtm = (DefaultTableModel) jtmercaderias.getModel();
        Mercaderias_C c = new Mercaderias_C();
        ArrayList<Mercaderias_C> all = c.SearchAll();
        
        for(int i=0; i < all.size(); i++ ){
            
            dtm.addRow(new Object[]{all.get(i).getId(), all.get(i).getCodigo(),
            all.get(i).getNombre(), all.get(i).getStock(), all.get(i).getPrecio(),
            all.get(i).getDescripcion()});
            
        }
        
    }
    
    public void search (String search) {
        
        String options = (String)jcbopciones.getSelectedItem();
        Mercaderias_C m = new Mercaderias_C();
        
        switch (options) {
            
            case "ID" : 
                DefaultTableModel model4id = m.Search4ID(search);
                jtmercaderias.setModel(model4id);
                break;
                
            case "Codigo de Fabrica" : 
                DefaultTableModel model4code = m.Search4Code(search);
                jtmercaderias.setModel(model4code);
                break;
                
            case "Producto":
                DefaultTableModel model4name = m.Search4Name(search);
                jtmercaderias.setModel(model4name);
                break;
                
            case "Descripcion" :
                DefaultTableModel model4desc = m.Search4Desc(search);
                jtmercaderias.setModel(model4desc);
        
        }
    
    }
    
    public static Integer getInt(String cadena){
        
        return ( (cadena == null || cadena.isEmpty() ) ? 0 : Integer.parseInt(cadena.trim()));
        
    }
    
    public static String getString(String cadena){
        
        return (cadena == null ? "" : cadena);
        
    }

}
