/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Control.CargosC;
import Control.ModoPago_C;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ModoPago_V extends javax.swing.JFrame {

    /**
     * Creates new form ModoPago_V
     */
    public ModoPago_V() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jbexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtmodopago = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbnew = new javax.swing.JButton();
        jbupdate = new javax.swing.JButton();
        jbdelete = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("MODOS DE PAGO");

        jbexit.setText("X");
        jbexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexitActionPerformed(evt);
            }
        });

        jtmodopago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Modo de pago"
            }
        ));
        jtmodopago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtmodopagoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtmodopago);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jbnew.setText("Nuevo");
        jbnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jbnew, gridBagConstraints);

        jbupdate.setText("Modoficar");
        jbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jbupdate, gridBagConstraints);

        jbdelete.setText("Eliminar");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jbdelete, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbexit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jbexit)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexitActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_jbexitActionPerformed

    private void jbnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnewActionPerformed
        
        this.Count();
        id = getInt(this.jTextField1.getText());
        name = JOptionPane.showInputDialog("Nuevo cargo: ");
        
        if (name.equals("")) {
            
            JOptionPane.showMessageDialog(rootPane, "Campo Vacio. \n Registro anulado.");
            
        } else {
        
            ModoPago_C a = new ModoPago_C(id, name);
            ModoPago_C already = a.Search(String.valueOf(id));
            
            if (already == null) {
                
                if (a.Insert()) {
                    
                    JOptionPane.showMessageDialog(rootPane, "Registro exitoso!");
                    
                } else {
                
                    JOptionPane.showMessageDialog(rootPane, "Ya existe: "+name+"");
                    
                    
                }
                
                dtm = (DefaultTableModel) jtmodopago.getModel();
                int rows = jtmodopago.getRowCount();
                for (int i = 0; rows < i; i++) {
                    
                    dtm.removeRow(0);
                    
                }
                
                this.update();
                this.star();
                
            }
        
        }
        
    }//GEN-LAST:event_jbnewActionPerformed

    private void jbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdateActionPerformed
        
        id = getInt(this.jTextField1.getText());
        name = JOptionPane.showInputDialog("Nuevo nombre: ");
        ModoPago_C upd = new ModoPago_C(id, name);
        
        if(upd.Update()){
            
            JOptionPane.showMessageDialog(rootPane, "Registro modficado");
            this.update();
            this.star();
            
        }else{
            
            JOptionPane.showMessageDialog(rootPane, "No modificado");
            
        }
        
    }//GEN-LAST:event_jbupdateActionPerformed

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
        
        String code = jTextField1.getText();
        ModoPago_C mp = new ModoPago_C();
        
        if(mp.Delete(code)){
            
            JOptionPane.showMessageDialog(this, "Eliminando satisfactoriamente");
            
        }else{
            
            JOptionPane.showMessageDialog(this, "Imposible eliminar");
            
        }
        
        this.update();
        this.star();
        
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        this.jTextField1.setVisible(false);
        this.jbdelete.setEnabled(false);
        this.jbupdate.setEnabled(false);
        this.star();
        
    }//GEN-LAST:event_formWindowOpened

    private void jtmodopagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtmodopagoMouseClicked
        
        this.jbdelete.setEnabled(true);
        this.jbupdate.setEnabled(true);
        dtm = (DefaultTableModel) this.jtmodopago.getModel();
        int selRow = this.jtmodopago.getSelectedRow();
        ModoPago_C car = new ModoPago_C();
        
        if(selRow != -1){
            
            String id = String.valueOf(dtm.getValueAt(selRow, 0).toString());
            ModoPago_C finded = car.Search(id);
            
            if(!(finded == null)){
                
                this.jTextField1.setText(String.valueOf(finded.getId()));
                
            }
            
        }
        
    }//GEN-LAST:event_jtmodopagoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoPago_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoPago_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoPago_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoPago_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModoPago_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbexit;
    private javax.swing.JButton jbnew;
    private javax.swing.JButton jbupdate;
    private javax.swing.JTable jtmodopago;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel dtm;
    private int id;
    private String name;
    
    private void Count () {
    
        try {
            
            ModoPago_C a = new ModoPago_C();
            jTextField1.setText(a.New());
            
        } catch (Exception e) {
            
            
            
        }
    
    }
    
    private void update () {
        
        int tam = jtmodopago.getRowCount();
        
        for (int i = 0; i < tam; i++) {
            
            dtm.removeRow(0);
            
        }
        
    }
    
    private void star () {
        
        dtm = (DefaultTableModel) jtmodopago.getModel();
        ModoPago_C c = new ModoPago_C();
        ArrayList<ModoPago_C> all = c.SearchAll();
        
        for(int i=0; i < all.size(); i++ ){
            
            dtm.addRow(new Object[]{all.get(i).getId(), all.get(i).getName()});
            
        }
        
        this.jTextField1.setText("");
        
    }
    
    public static Integer getInt(String cadena){
        return ( (cadena == null || cadena.isEmpty() ) ? 0 : Integer.parseInt(cadena.trim()));
    }

}
