/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Control.TipoUsuario_C;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class TipoUsuario_V extends javax.swing.JFrame {

    /**
     * Creates new form TipoUsuario_V
     */
    public TipoUsuario_V() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttipousuario = new javax.swing.JTable();
        bdelete = new javax.swing.JButton();
        bnew = new javax.swing.JButton();
        breport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        bexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridBagLayout());

        ttipousuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Tipo de usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ttipousuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttipousuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ttipousuario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        bdelete.setText("Eliminar");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 72, 0, 10);
        jPanel2.add(bdelete, gridBagConstraints);

        bnew.setText("Nuevo");
        bnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(bnew, gridBagConstraints);

        breport.setText("Ver Reporte");
        breport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        jPanel2.add(breport, gridBagConstraints);

        jLabel1.setText("Tipos de Usuarios");

        jTextField1.setText("jTextField1");

        bexit.setText("Salir");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(bexit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bexit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewActionPerformed
        
        this.Count();
        number = getInt(this.jTextField1.getText());
        name = JOptionPane.showInputDialog("Nuevo usuario: ");

        if (name == null) {
            
            int response = getInt(name);
            
            if (response == JOptionPane.CANCEL_OPTION) {
                
                JOptionPane.showMessageDialog(rootPane, "Cancelado");
                
            }
            
            return;
            
        }
        
        if (name.equals(null)) {
        
            JOptionPane.showMessageDialog(rootPane, "Campo vacio");
            
        } else {
        
            TipoUsuario_C a = new TipoUsuario_C(number, name);
            TipoUsuario_C already = a.Search(String.valueOf(number));
            
            if (already == null) {
                
                if (a.Insert()) {
                    
                    JOptionPane.showMessageDialog(rootPane, "Registro exitoso!");
                    
                } else {
                
                    JOptionPane.showMessageDialog(rootPane, "Ya existe: "+name+"");
                    
                    
                }
                
                t_tipousuario = (DefaultTableModel) ttipousuario.getModel();
                int rows = ttipousuario.getRowCount();
                for (int i = 0; rows < i; i++) {
                    
                    t_tipousuario.removeRow(0);
                    
                }
                
                this.update();
                this.star();
                
            }
        
        }
        
    }//GEN-LAST:event_bnewActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        
        String code = jTextField1.getText();
        
        if(tu.Delete(code)){
            
            JOptionPane.showMessageDialog(this, "Eliminando satisfactoriamente");
            
        }else{
            
            JOptionPane.showMessageDialog(this, "Imposible eliminar");
            
        }
        
        this.update();
        this.star();
        
    }//GEN-LAST:event_bdeleteActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_bexitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        this.jTextField1.setVisible(false);
        this.bdelete.setEnabled(false);
        this.star();
        
    }//GEN-LAST:event_formWindowOpened

    private void ttipousuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttipousuarioMouseClicked
        
        this.bdelete.setEnabled(true);
        t_tipousuario = (DefaultTableModel) this.ttipousuario.getModel();
        int selRow = this.ttipousuario.getSelectedRow();
        
        if(selRow != -1){
            
            String id = String.valueOf(t_tipousuario.getValueAt(selRow, 0).toString());
            TipoUsuario_C finded = tu.Search(id);
            
            if(!(finded == null)){
                
                this.jTextField1.setText(String.valueOf(finded.getId()));
                
            }
            
        }
        
    }//GEN-LAST:event_ttipousuarioMouseClicked

    private void breportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breportActionPerformed
        
        tu.showTU();

    }//GEN-LAST:event_breportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoUsuario_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoUsuario_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoUsuario_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoUsuario_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoUsuario_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bnew;
    private javax.swing.JButton breport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable ttipousuario;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel t_tipousuario;
    private int number;
    private String name;
    private final TipoUsuario_C tu = new TipoUsuario_C();

    private void Count () {
    
        try {
            
            jTextField1.setText(tu.New());
            
        } catch (Exception e) {
            
            
            
        }
    
    }
    
    private void update () {
        
        int tam = ttipousuario.getRowCount();
        
        for (int i = 0; i < tam; i++) {
            
            t_tipousuario.removeRow(0);
            
        }
        
    }

    private void star () {
        
        t_tipousuario = (DefaultTableModel) ttipousuario.getModel();
        ArrayList<TipoUsuario_C> all = tu.SearchAll();
        
        for(int i=0; i < all.size(); i++ ){
            
            t_tipousuario.addRow(new Object[]{all.get(i).getId(), all.get(i).getName()});
            
        }
        
        this.jTextField1.setText("");
        
    }
    
    public static Integer getInt(String cadena){
        return ( (cadena == null || cadena.isEmpty() ) ? 0 : Integer.parseInt(cadena.trim()));
    }
    
    public static String getString(String cadena){
        return (cadena == null ? "" : cadena);
    }
    
}
